### PR TITLE
fixed breaking typo

### PR DESCRIPTION
**Pull request by ExpandingMan**
This was tiny but broke the method it lived in.

### CODE REVIEW

**Review by mattBrzezinski — APPROVED** [review]
bors r+

**Review by iamed2 — APPROVED** [review]

**Comment by ExpandingMan** [comment]
I get burned by that formatting every single time... at least I can plausibly claim it was not my fault this time :laughing:

**Comment by ExpandingMan** [comment]
Fun fact: I checked the blame and this typo was my fault in the first place.

**Comment by mattBrzezinski** [comment]
> Fun fact: I checked the blame and this typo was my fault in the first place.

image

**Pull request merged**
